### ISSUE TITLE
selenium q.

### ISSUE THREAD

**Issue by antonysama** [kaobeosolu78/Scientific_Study_Analysis#1]
Thanks for sharing! That it can scan research is interesting!

I installed chromium, selenium and set their paths. Then I ran ' python get_sci_study.py'
 and got the following error (platform python 3.6 on linux stand-alone computer):

`Traceback (most recent call last):
  File "get_sci_study.py", line 29, in <module>
    get_study_page("weed")
  File "get_sci_study.py", line 8, in get_study_page
    driver = webdriver.Chrome(chromedriver)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /content/drive/My Drive/Scientific_Study_Analysis/chromedriver unexpectedly exited. Status code was: -6`

**Comment by kaobeosolu78** [comment]
I'm not too familiar with Linux but according to this: https://stackoverflow.com/questions/18674092/how-to-implement-chromedriver-in-selenium-in-linux-platform
 your system expects the chromedriver to be in a certain location (specifically /usr/bin/google-chrome). This might be contributing to the issue you are having

**Comment by antonysama** [comment]
Thank you, shall try this.
